In [2]:
import pandas as pd
f = 'transaction_data.csv'
raw = pd.read_csv(f)

In [22]:
import datetime
data = raw.sample(10000)
str_type = ['UserId', 'TransactionId', 'ItemCode']
def date_time_converter(cell):
    try:
        return datetime.datetime.strptime(cell, "%a %b %d %H:%M:%S IST %Y")
    except:
        print(cell)
data.TransactionTime = data.TransactionTime.apply(date_time_converter)
data.loc[:, str_type] = data.loc[:, str_type].astype('string')

In [24]:

date_condition = data.TransactionTime.map(lambda x: x.year==2018)
conditions = data.Country.eq('United Kingdom') & ~data.UserId.eq('-1') & date_condition
data[conditions]

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
1,337701,6283376,2018-12-26 09:06:00,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
3,380478,6044973,2018-06-22 07:14:00,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
6,345954,6162981,2018-09-28 10:51:00,471576,NATURAL SLATE CHALKBOARD LARGE,9,6.84,United Kingdom
8,339822,6255403,2018-12-10 09:23:00,1783845,MULTI COLOUR SILVER T-LIGHT HOLDER,36,1.18,United Kingdom
10,316848,6262696,2018-12-15 10:05:00,460215,RED HARMONICA IN BOX,36,1.73,United Kingdom
...,...,...,...,...,...,...,...,...
1083808,355488,6160286,2018-09-25 09:11:00,478191,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,72,1.73,United Kingdom
1083809,321531,6037493,2018-06-16 09:57:00,441693,JUMBO BAG CHARLIE AND LOLA TOYS,6,2.88,United Kingdom
1083811,352191,5973242,2018-04-16 10:37:00,466599,LOVEBIRD HANGING DECORATION WHITE,24,1.18,United Kingdom
1083816,324765,5945500,2018-03-23 06:26:00,470883,REGENCY CAKESTAND 3 TIER,48,15.12,United Kingdom
1083817,351645,6118145,2018-08-21 08:21:00,471849,HEART OF WICKER SMALL,9,2.28,United Kingdom